Shape sorting game
smccauley14/ZenDen pull request #17
Opened 2024-04-19 22:07 UTC by dmclaughlin104

Created a basic gameplay loop for a shape sorting game. Wooden blocks appear in a random position in the middle of the screen, while their respective 'holes' appear in random positions along the sides. When all shapes are sorted in their correct holes, the shapes and holes are shuffled into new positions. Shapes glow yellow while being interacted with, and red when they are resting in the wrong spot. When they're in more or less the right spot, they will automatically move to centre of the hole and slot through it.

2024-04-21 21:56 UTC, eoloughlin05 commented on Assets/Scripts/DragDropToDistance.cs
> +    private bool isMoving = false; // Flag to track whether movement is in progress
Could we change this to 'isShapeMoving'?

2024-04-21 21:57 UTC, eoloughlin05 commented on Assets/Scripts/DragDropToDistance.cs
> +    private bool isAtMiddle = false;//to check whether object has reached middle;
Could we change this to 'isShapeAtMiddleOfShapeSpace' or something indicating where the middle is?

2024-04-21 22:01 UTC, eoloughlin05 commented on Assets/Scripts/DragDropToDistance.cs
> +    private void MoveBackWard()
We can change the method name of this to 'MoveObjectThroughHole' which would remove the comment line above.

2024-04-21 22:03 UTC, eoloughlin05 commented on Assets/Scripts/DragDropToDistance.cs
> +        //GetComponent<Rigidbody>().useGravity = false;
This comment can be removed if no longer required.

2024-04-21 22:04 UTC, eoloughlin05 commented on Assets/Scripts/DragDropToDistance.cs
> +        //GetComponent<Rigidbody>().useGravity = true;
This comment can be removed if it is no longer required.

2024-04-21 22:07 UTC, eoloughlin05 commented on Assets/Scripts/DragDropToDistance.cs
> +    //followed this tutorial for basic touchscreen dragging: https://www.youtube.com/watch?v=zo1dkYfIJVg
Can this line be removed?

2024-04-21 22:08 UTC, eoloughlin05 commented on Assets/Scripts/DragDropToDistance.cs
> +
Lines 35 - 37 can be removed as it's just white space.

2024-04-21 22:09 UTC, eoloughlin05 commented on Assets/Scripts/DragDropToDistance.cs
> +
This line can be removed too - re. white space

2024-04-21 22:09 UTC, eoloughlin05 commented on Assets/Scripts/DragDropToDistance.cs
> +
This line can be removed - white space

2024-04-21 22:09 UTC, eoloughlin05 commented on Assets/Scripts/DragDropToDistance.cs
> +
This line can be removed - white space

2024-04-21 22:11 UTC, eoloughlin05 commented on Assets/Scripts/RotatingCubesController.cs
> +
These lines can be removed if the code isn't required anymore.

2024-04-21 22:12 UTC, eoloughlin05 commented on Assets/Scripts/RotatingCubesController.cs
> +            //_rotation.x = -(_mouseOffset.x + _mouseOffset.y) * _sensitivity;
These lines can be removed if they're no longer required

2024-04-21 22:13 UTC, eoloughlin05 commented on Assets/Scripts/RotatingCubesController.cs
> +
These lines can be removed if they're not required.

2024-04-21 22:14 UTC, eoloughlin05 commented on Assets/Scripts/ShapeSorting_GameManager.cs
> +
White space that can be removed

2024-04-21 22:14 UTC, eoloughlin05 commented on Assets/Scripts/ShapeSorting_GameManager.cs
> +
Extra line can be removed - white space

2024-04-21 22:16 UTC, eoloughlin05 commented on Assets/Scripts/ShapeSorting_PerimeterManager.cs
> +
White space - can be removed

2024-04-21 22:17 UTC, eoloughlin05 commented on Assets/Scripts/ShapeSorting_PerimeterManager.cs
> +
These lines can be removed as the Update method is empty and not in use.

2024-04-21 22:21 UTC, eoloughlin05 requested changes
I have tested this out Damien and it looks great. Brilliant work!

Just a few comments; very minor changes such as changing a couple of the naming conventions so that it is clearer in the code what is happening. There are a couple of unused or empty methods that can be removed and some comment lines also which I have marked. The last thing is white space; where there are a lot of extra blank lines that can be removed. I have marked a few of these, but not them all, just to give you an example of where I'm talking about. If there's anything that doesn't make sense, please just let me know. I will review it again as soon as changes are made. Thanks!

2024-04-21 23:10 UTC, dmclaughlin104 commented
Thanks for this, Erin.

I've now updated the scripts to remove blank space and I've also deleted a few older scripts that weren't currently in use or which have been superseded (including the RotatingCubes script). I've also made the red wrong highlight more obvious now by making the whole front of the shape red.

I'm up for adding sound effects etc., but I think I they should be in-keeping with the new sounds that we've recorded for the colour-sorting game.

In terms of priorities, I'll probably need to look at bringing in the sound effects into the colour-sorting game first, and then I look at doing the same for the shape-sorting game.

2024-04-25 22:29 UTC, eoloughlin05 approved these changes

2024-04-25 22:30 UTC, merged